### ISSUE TITLE
Open in office action and webdav is not available in the 7.0 beta package

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#10]
These kinds of office protocol links should work even without the UI layer:

`ms-word:ofe|u|http://example.com/Root/Workspace/DocLib/Lorem.docx`

Currently Word cannot open the file.

**Comment by borsi** [comment]
It may be working now. Someone needs to test it.

**Comment by tusmester** [comment]
To make this work, we have to move the _WebdavOpenAction_ class and corresponding app content (currently hiding in the _WebPages_ component) to the _Services_ layer. This can be done, as there is no UI for this action, no need to ship it in WebPages.

**Comment by iviczl** [comment]
With a correctly configured Windows authentication it does work for me. (There was a bug although: the action's Initialize method compared the file extension in a case sensitive manner. I changed it into case insensitive and pushed into the develop branch.)
