### ISSUE TITLE
OpenTree function

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#1005]
Write a REST function that provides a data source for the client's tree-view at the page load time. The response is a content tree structure that contains all child elements of the related ancestors (not the full subtree).

Signature:
`OpenTree(contextPath, rootPath, projection, withLeaf)`
example
`OpenTree("Root/Content/a/bb/CCC", "Root/Content", "Id,Name,Type,Icon", false)`

Fix these problems:
- [ ] The single-element tree should be returned instead of throwing an error.
- [ ] The context element needs to be in the list.
- [x] Eliminate nullreferece error when the root is the /Root (incomplete permissions?)

**Comment by tusmester** [comment]
@kavics why do we need a new parameter (projection), why don't we use **$select**?
