### ISSUE TITLE
Repository for site images

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#105]
Create a new repository which can hold our predefined projects so if someone needs more projects at once, she doesn't need to pull every project separately but can find them bundled together here.

The most important question is what this should be called. To decide, fight in the comments **TO THE DEATH**. 💀

**Comment by borsi** [comment]
* sn-site-templates
* sn-project-templates
* sn-site-images
* sn-death-excavator
* sn-happy-puppy
* sn- combination-wrench

**Comment by iviczl** [comment]
It should be a pool for site images.

**Comment by borsi** [comment]
**VS Project templates** is a winner by the width of a dog's hair

**Comment by iviczl** [comment]
It is a very dark day.
