### ISSUE TITLE
Messaging & cache study

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#106]
- Research how messaging and cache now works in sn
- Research industry standards and implementation opportunities
- Come up with a plan for modernizing our Messaging and Caching interfaces

## Considerations
- Don't forget to consider Security when researching this backlog item
- Communications between webnodes has to be solved
- We have not been considering RAM limit so far. This can be a problem from now on.

## Output:
- Messaging refactor epic/story (#351 RabbitMQ prototype)
- Caching refactor epic/story

**Comment by tusmester** [comment]
Separate issues will be created for these features.
A related one: #351 (RabbitMQ prototype)
