### ISSUE TITLE
Indexing study

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#107]
- Research sn indexing and the possibilities of having one centralized index instead of distributed index nodes
- Research azure options: services or vm's
- Come up with an implementation *plan* for the refactor
## Output
- A story/epic for refactoring Indexing

## Considerations
- A user might want to choose between azure services or azure vm's. Should we give her the possibility to do so?
- Is azure search the best solution for us?
- What happens if one wants to migrate her system from one solution (service) to an other (a vm)? How should we support this?
- Sensenet's own query language should stay because of backwards compatibility

**Comment by iviczl** [comment]
Azure Search provides a single index access point and can successfully be a substitute for local Lucene index.
In Azure we should support three forms of deployment: app service web apps, virtual machines and service fabric. (the cloud services alternative is a legacy one, so we leave it out)
