### ISSUE TITLE
[BUG] Newly added fields in a ctd are not added to the (client)schema

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#1075]
# 🐜 Bug Report

I've tried to add some custom fields to a content type definition and the modifications are saved successfully, but the fields are not available on the Edit and New views because the new fields are not generated to the client schema generated by `GetSchema`

## 👉 Steps To Reproduce

1. Login to the admin-ui with BuiltIn\admin
2. Go to Content Types
3. Open ImageLibrary ctd for edit by double click on its row in the grid
4. Add the following two new fields to the xml
```
   <Field name="Test" type="Reference">
    <DisplayName>Author</DisplayName>
  <Description>A field for the author user</Description>
  <Configuration>
    <AllowMultiple>false</AllowMultiple>
    <SelectionRoot>
        <Path>/Root/IMS/Public</Path>
    </SelectionRoot>
    <AllowedTypes>
        <Type>User</Type>
    </AllowedTypes>
    <Compulsory>false</Compulsory>
    <VisibleBrowse>Show</VisibleBrowse>
    <VisibleEdit>Show</VisibleEdit>
    <VisibleNew>Show</VisibleNew>
  </Configuration>
</Field>
```
5. Save the ctd
6. Go to Content/IT
7. Right click on Image gallery and choose Edit
8. Or click on Add new and choose Image gallery

## 😯 Current behavior

The field is missing from the views and also from the generated client schema.

## 🤔 Expected behavior

The newly added fields should be there in the generated client schema

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/6968860/91707871-c1eb8380-eb80-11ea-9e8c-901c0aac386f.png)
![image](https://user-images.githubusercontent.com/6968860/91707920-d29bf980-eb80-11ea-92d4-dbfd3c58bb1e.png)

**Comment by kavics** [comment]
I don't reproduce this on the backend. Uploading CTD fires an invalidation event that causes the client metadata provider refresh. So this bug probably not a backend error.

A possible cause of the error is a frontend deficiency: after any CTD modification, the schema needs to be reloaded.
