### ISSUE TITLE
Make the Preview action visible only for contents with an appropriate type

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#1101]
There's a whitelist for file types for which preview can be generated but this functionality is not connected with the actions, so the user can see and use the preview action on content that will never have a preview. 

Acceptance:
The Preview action should be returned in the Actions list, when the related content has one of the appropriate (whitelisted) types.

Backend feature to use: `IOperationMethodPolicy`

**Comment by tusmester** [comment]
Preview action is no longer visible in the context menu or in the actions list.
