### ISSUE TITLE
[SNaaS] User related content that should not be deleted

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#1108]
- users should not delete themselves
- the connected repo owner should not be deleted from the repository
- the Public/Administrators group should not be deleted

**Comment by tusmester** [comment]
+1 maybe: a repo always has to have an owner, so the RepoOwner field must never be empty.

**Comment by herflis** [comment]
tasks merged with [#1162 ](https://github.com/SenseNet/sensenet/issues/1162)
