### ISSUE TITLE
Replace console installer with automatic db creation and package installer

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#1120]
Instead of console installer, webapp should create the db and install packages.

- [ ] automatic db creation if it does not exist
- [ ] convert current install package to a new format
   - [ ] load install package from where? 
       - current library (quickest solution, but size issues may arise)
       - download from a custom url? (_later_)
       - download from a well-known package feed (nuget?, github?) (_later_)

**Comment by tusmester** [comment]
Transferred to https://github.com/SenseNet/sensenet/issues/1530
