### ISSUE TITLE
Allowed childtypes rethink/redesign/refactor

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#1142]
- what can and cannot be put in a container
- inheritance: inherited types may be added automatically by adding the 'parent'
- handle on the ui as a separate allowed childtypes setting view (like permissions editor) not as a field on the edit view
- search for allowed childtypes (where is it allowed)
- separate lists for 'set in the ctd', allowed, denied types for a content

**Comment by tusmester** [comment]
Replaced by #1616
