### ISSUE TITLE
[BUG] Some of the emojis are changed to question marks in LongText fields

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#1149]
This issue can be reproduced using the blog post synchronizing tool

**Comment by haardikdharma10** [comment]
Hey @herflis, This is something not related to the issue. But going through the README, I see a lot of broken hyperlinks. Can I go ahead and fix them because I see most of the update readme pr's are marked invalid and closed (not merged). Let me know what you think:)

**Comment by herflis** [comment]
Hi @haardikdharma10 , thanks for reporting the broken links. Sorry, but these texts (README.md, etc) are currently being updated by us connected to the website redesign, so we'll work it out :) If you are interested in helping us during the Hacktoberfest, look at the tasks on the [dedicated board](https://github.com/orgs/SenseNet/projects/7) and feel free to choose one. :)
