### ISSUE TITLE
[BUG] GetSchema returns enum index value not the actual value

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#1150]
## Steps to reproduce:
1. Login to admin-ui
2. Open the dev toolbars network tab an check the response of the GetSchema
3. Search for `TextType` in the response of GetSchema

## Current behavior

TextType's value is 0 in the schema response

## Expected behavior

TextType's value should be `LongText`

![image](https://user-images.githubusercontent.com/6968860/94914144-befaf000-04aa-11eb-9d5a-bb7d4aa40724.png)

**Comment by pusztaienike** [comment]
It is working 👍
