### ISSUE TITLE
Prevent admin users from lock out themselves from the repository

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#1162]
There must be at least one **enabled** user in Public/Adminstrators.

- [x] Last user should not be removed from the Member field of the Public/Administrators group
- [x] The last user in Public/Administrators group cannot be set to disabled
- [x] Do not remove a user from Members if he is the only enabled user  and only disabled user(s) remain
- [x] The user that is the last one remaining in the Members of Public/Administrators cannot be deleted at all
- [x] users should not delete themselves
- [x] users should not be able to set themselves to disabled
- [x] the Public/Administrators group should not be deleted

**Comment by tusmester** [comment]
Related: #1108

**Comment by herflis** [comment]
tasks merged with [#1108](https://github.com/SenseNet/sensenet/issues/1108)

**Comment by herflis** [comment]
@tusmester I was able to delete myself as businesscat from the repository :( the other tasks are done
