### ISSUE TITLE
Remove duplicate MD file

### ISSUE THREAD

**Issue by HeroicHitesh** [SenseNet/sensenet#1178]
While cloning the repository I got a warning 
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'docs/JAMstack.md'
  'docs/jamstack.md'
```
And after looking through docs I found the 2 files [docs/JAMstack.md](https://github.com/HeroicHitesh/sensenet/blob/master/docs/JAMstack.md) and [docs/jamstack.md](https://github.com/HeroicHitesh/sensenet/blob/master/docs/jamstack.md) to be containing same content. 

If it was by mistake we can remove one of them and if these files are created intentionally(which I don't think is the case, due to the same content) we can rename them to avoid confusion.

I would be happy to send a PR for this issue.

**Comment by herflis** [comment]
Hi @HeroicHitesh , okay let's do this, but you could get the extra swag only if you choose one from [these issues](https://github.com/orgs/SenseNet/projects/7) ;)

**Comment by HeroicHitesh** [comment]
@herflis Yes I am looking into Cypress Docs and setting up the project, once that is done, I'll ask for an issue from the provided list.

**Comment by HeroicHitesh** [comment]
And just to confirm, I am removing [docs/jamstack.md](https://github.com/HeroicHitesh/sensenet/blob/master/docs/jamstack.md) file. And not touching the other file.

**Comment by HeroicHitesh** [comment]
@herflis Created a PR which resolves this issue. 

Also, I had another doubt🤔 where can I contact regarding the swags?
I was supposed to receive some last year too, but haven't received them till now😩 I tried contacting various email-ids that were related to SenseNet, which I could find from my inbox. But got nothing in response.
Can please help out on this too😶

**Comment by herflis** [comment]
@HeroicHitesh I'm sorry to hear that :( Let me talk with my colleagues who arranged for the t-shirts to be posted and they will contact you via email.
