### ISSUE TITLE
SnAdmin type loader exception should display more info

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#12]
When something is wrong with the available types (e.g. there is a missing type or a wrong version of for example Newtonsoft.Json), _SnAdmin_ (or _SnAdminRuntime_) fails to execute. The necessary information is **displayed in the trace log**, but **not on screen (console window)**, because at that time even the logger module is not yet initialized. 

We should **handle type loader exceptions** and display the **LoaderException** property (not InnerException!) on the console so that the user knows the error without starting DebugView.

**Comment by tusmester** [comment]
(@maros has started working on this, waiting for the pull request)

**Comment by borsi** [comment]
hi @marosvolgyiz! thanks for the grab. Are you still working on this?
