### ISSUE TITLE
[BUG] Can not create new CTD on netcore test with BusinessCat

### ISSUE THREAD

**Issue by taki9** [SenseNet/sensenet#1202]
Repository: https://netcore-service.test.sensenet.com
User: Business Cat

![image](https://user-images.githubusercontent.com/8918642/98663438-650f0500-2349-11eb-897d-e75e9c29bafb.png)

Response:
```json
{
  "error": {
    "code": "NotSpecified",
    "exceptiontype": "SenseNetSecurityException",
    "message": {
      "lang": "en-us",
      "value": "Access denied."
    },
    "innererror": null
  }
}
```

**Comment by herflis** [comment]
The actual problem was that the user had no See permission on the parent type (ItemList).
