### ISSUE TITLE
Audit log does not work if the db collation is case sensitive

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#121]
When **EntLib** tries to write an Audit event to the db, a SQL exception is thrown about not receiving the _EventId_ parameter.

```txt
Procedure or function 'proc_LogWrite' expects parameter '@EventId', which was not supplied.
```

This does not happen if the db collation is case insensitive (CI), only if it is case sensitive (CS), so this is probably related to a column/property name somewhere with a different casing (EventID or Eventid).

Classes to inspect: _EntLibLoggerAdapter_, _SnXmlFormatter_

Repro steps: 

1. create an empty db manually
2. set the collation on the db to a case sensitive one (e.g. in SQL Management Studio)
3. install sensenet Services into this db with forcedreinstall:true parameter
4. log in --> this should trigger an audit log event (or create a content)

**Comment by kavics** [comment]
Additionally:
Enterprise library calls with these:
**eventID**, **priority**, **severity**, **title**, **timestamp**, **machineName**, AppDomainName, ProcessID, ProcessName, ThreadName, Win32ThreadId, **message**, **formattedmessage**, LogId

proc_LogWrite expects these: 
**EventId**, **Priority**, **Severity**, **Title**, **Timestamp**, **MachineName**, AppDomainName, ProcessID, ProcessName, ThreadName, Win32ThreadId, **Message**, **FormattedMessage**, LogId
