### ISSUE TITLE
New demo and test sites

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#124]
### manatee.sensenet.com
- [x] DONE
- Description: Daily build of latest unstable
- Purpose: Test the release candidate before release
- Version/Branch: release candidate (services, webpages, etc)
- Rebuild period: daily
- Visibility: Inner
- Measurement: Not necessary

### demo.sensenet.com
- [ ] DONE
- Description: A global demo site for everyone to demo the functionality of the system. 
- Purpose: Sales and marketing and anyone, who'd like to show off the features of a SN6 demo system, can do it here.
- Version/Branch: Sensenet 6.5.4.x
- Rebuild period: When the system fails or brakes
- Visibility: Inner
- Measurement: GTM + analytics + hotjar to measure usable features

### dev.demo.sensenet.com
- [ ] DONE
- Description: A site for showcasing the developer platform qualities of sn: latest services and workspaces, with a minimalistic frontend where users can run javascript snippets and see the outcome
- Purpose: Test whether developers are a real customer segment and if so, gather their feedback through this site
- Version: Latest sn7 + client-js + react/aurelia
- Rebuild period: Daily - users can programmatically create and delete content, things can go awry pretty fast
- Visibility: Everyone
- Measurement: GTM + analytics + hotjar + custom metrics?

### dms.demo.sensenset.com
- [ ] DONE
- Description: A site for showcasing the document management features of SN7 - the MVP, which we build continuously and collect user feedback from it
- Purpose: Test which document management features our customers want to use and how. Measure activity, A/B test features and gather feedback through surveys and user tests
- Version: Latest sn7 + required content package + client-js + react/aurelia
- Rebuild period: Daily - users can programmatically create and delete content, things can go awry pretty fast
- Visibility: Everyone
- Measurement: GTM + analytics + hotjar + custom metrics?

### [FOR FUTURE REFERENCE] 
future.demo.sensenet.com -> Future demo.sensenet.com, when a complete demo is ready to showcase. Same purpose as the sn6 one, but that will be deprecated by then.
Description: A global demo site for everyone to demo the functionality of SN7. 
Purpose: Sales and marketing and anyone, who'd like to show off the features of a SN7 demo system, can do it here.
Version/Branch: Latest sn7 services + webpages + workspaces + notifications + *
Rebuild period: When the system fails or brakes, otherwise when patches are released
Visibility: Everyone
Measurement: GTM + analytics + hotjar to measure usable features

**Comment by tusmester** [comment]
My 2 cents for the dev demo url:

developers... --> dev.demo... :)
