### ISSUE TITLE
NodeQuery removal in three phases

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#129]
- [x] Convert all NodeQueries to content query or calling QueryXXXX method.
- [x] 2h NodeQuery be static. Remain only these methods: public static NodeQueryResult QueryXXXX.
- [ ] 8h Depending on the decision (backward compatibility)
  - [ ] Replace QueryXXXX methods to internal query router technique.
  - [ ] Create other QueryXXXX methods as shortcuts.

**Comment by kavics** [comment]
Xxxxxx has already been static.
