### ISSUE TITLE
Custom action is needed for regenerating secrets

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sensenet#1303]
The settings menu of admin-ui should have a page where the user can copy her/his client Id and get/regenerate personal access token.
For these cases new custom actions are needed for the actual repo. 

**GetClients
RegenerateSecret**

![image](https://user-images.githubusercontent.com/22347393/106584219-3bc7d480-6546-11eb-84ca-243704a571d8.png)

![image](https://user-images.githubusercontent.com/22347393/106584277-4b471d80-6546-11eb-8d20-090546eae415.png)

**Comment by tusmester** [comment]
The two new actions:

```
GetClientsForRepository
RegenerateSecretForRepository
```
