### ISSUE TITLE
CqlParser unit tests

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#133]
Tests only for SnQuery AST (SenseNet.Search.Parser.SnQueryPredicate class and SenseNet.Search.Parser.Predicates namespace). 150-200 unit tests partially from old version e.g. budapest branch or latest release: 

$/SenseNet/Releases/enterprise/v6.5/servicepack/Source/SenseNet/Tests/LuceneParser/ParserTest.cs.

## Acceptance criteria
- [ ] Code review is done by at least 1 person other than @kavics

**Comment by tusmester** [comment]
@kavics please add more info about what to review (e.g. test project, class).

**Comment by kavics** [comment]
I would like to know that there is enough test case and the basic test methods are valid e.g. these:
**`private SnQuery Test(string queryText, string expected = null)`** and **`private void TestError(string queryText)`** in the **`SenseNet.Search.Tests.CqlParserTests`**.

**Comment by kavics** [comment]
I write 4 additional tests containing 148 test cases: **Search_Parser_AstToString_MultiBool*** and a control method: **BoolTest**. These cover all mentioned missing topics.
