### ISSUE TITLE
2 hours earlier date time in content explorer

### ISSUE THREAD

**Issue by swacsa** [SenseNet/sensenet#134]
When I create or modify some content in the content explorer the date time is 2 hours earlier than my current time, maybe it's UTC format. 
Is is a bug, or it's a feature which could be change? 

![utc_time](https://user-images.githubusercontent.com/11719551/28622045-5da1110e-7213-11e7-8a89-d43baa42a58c.png)

**Comment by frunkad** [comment]
Can I take this up? @herflis

**Comment by tusmester** [comment]
Closed as obsolete.
