### ISSUE TITLE
Remove the password request step from the repository assignment process

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#1382]
Since we are able now to move users with their password from one repository to another, we could skip the related step from the user's repository assignment flow. It is now a bit confusing and uncomfortable for the users to do this additional step, so to make the whole process a bit simpler, the `SyncUser` action should not only copy the user content to the other repository but also send the password of the user in the snover. 

### Issues
- copying password hash is not enough, we need to set the `CreationDate` of the new user to be the same as the original, otherwise passwords would not match with the salt when the user logs in.
- if the user registers using an **external auth provider** (e.g. Google), we have to ask for a new password in the following places:
   - when the user registers in SNaaS for the first time (see automatic repo creation #1417)
   - when the user clicks the New repository button 
- repo creation is a background process. We need to find a solution for the case when this task _fails_ (e.g. because of environment issues, not enough repositories, etc). Do we save the provided password somewhere (not a very nice solution) or ask for it again? Maybe we should fall back to the old force reset password workflow in these cases.

**Comment by tusmester** [comment]
Backend side is ready, but the feature has been removed temporarily. Commented lines have to be re-added before we want to test this.
