### ISSUE TITLE
There is a typo in VersionInfo response

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sensenet#1435]
There is a typo in the response of VersionInfo: 
![image](https://user-images.githubusercontent.com/22347393/116407371-00316380-a832-11eb-8396-3f75c26dccd2.png)
The LatestReleases has an attribute with the name of: "ReleaseData"
It should be 'ReleaseDate' instead.

**Comment by herflis** [comment]
Duplicate issue :)
