### ISSUE TITLE
[BUG] Identity server incidents

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#1486]
The snaas [status page](https://status.sensenet.cloud/) shows major incidents at the identity server regurarly. We should check what these incidents are.

[https://status.sensenet.cloud/incidents/46570](https://status.sensenet.cloud/incidents/46570)

![image](https://user-images.githubusercontent.com/6968860/119945365-a4273f80-bf95-11eb-9ad6-0eb919799864.png)

**Comment by VargaJoe** [comment]
it was a misconfiguration and have been fixed
