### ISSUE TITLE
Copy and Move dialog window redesign

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sensenet#1526]
### The new Copy to / Move to dialog behavior
- The header should show the **display name** of the target container (Copy "MyArticle" to Archive). This should change whenever I navigate in the tree up and down in the dialog. 
- When the dialog opens,  **the target is the current folder**.
- The Submit button should always be enabled.
- **Remove the checkboxes**: no selection needed, the target is always the current folder displayed in the header.
- Copy and Move dialogs should behave the same.

![image](https://user-images.githubusercontent.com/18169555/175501788-1b26b3f9-8e44-441b-a332-7188fc32061a.png)

**Comment by tusmester** [comment]
Cannot reproduce this, pls provide more info:
- you tried to copy /Root under /Root/Content?
- which user were you logged in with?
- admin ui or console app?
