### ISSUE TITLE
Content with allowed custom CTD type can not be created

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sensenet#1607]
the error is similar or the same as #1608, but from custom client app
it occurs when the CTD is named explicitly as "Page", so the given repro steps accordingly

Process and error message:
- I've created a custom client app that connects with Personal Access Token 
- the app creates 3 CTD: A, Page, C
- A CTD allowed child types contains Page
- Page CTD allowed child types contains C
- allow A child type on /Root/Content
- one A container folder has been created under /Root/Content
- multiple Page container folders have been created under /Root/Content/A
- tried to create C type content under one of the Page type content
- Exception:  Cannot save the content  /Root/Content/A/Page/C  because its ancestor does not allow the type  C . Ancestor: /Root/Content/A (A). Allowed types: Folder, File, Page, SystemFolder 

From admin ui when try to add a content under B, I can not see the custom allowed child types.

Custom app use sn-client-dotnet package ```Content.UploadAsync``` to create a ctd.

**Comment by VargaJoe** [comment]
"Page" is the CTD name where allowed child types are not working

**Comment by tusmester** [comment]
Cannot repro this, pls provide more details and samples. Tried all the steps above manually and also programmatically from the tool (with the public admin token), no luck (I mean it worked :) ).

**Comment by VargaJoe** [comment]
One of yout ctd has the name "Page"? I think the problem was that in my case. Maybe "Page" type isan exception?

**Comment by VargaJoe** [comment]
the error is similar or the same as 1608, but from custom client app
it occurs when the CTD is named explicitly as "Page", so the given repro steps accordingly

I've created a custom client app that connects with Personal Access Token
the app creates 3 CTD: A, Page, C
A CTD allowed child types contains Page
Page CTD allowed child types contains C
allow A child type on /Root/Content
one A container folder has been created under /Root/Content
multiple Page container folders have been created under /Root/Content/A
tried to create C type content under one of the Page type content
Exception: Cannot save the content /Root/Content/A/Page/C because its ancestor does not allow the type C . Ancestor: /Root/Content/A (A). Allowed types: Folder, File, Page, SystemFolder

**Comment by kavics** [comment]
This is not a bug, but a feature. In enabling the child type feature, the "Page" content type, behaves in a transitive way, like the "Folder" content type. See the new acceptance tests:
- AllowedChildTypes_Bug1607_Transitive_Page: reproduction test for these issues.
- AllowedChildTypes_Bug1607_Transitive_Folder: transcript of the previous test, where "page" was replaced by "folder".

**Comment by tusmester** [comment]
Developers will get an error when trying to define allowed child types on a transitive CTD. #1729
