### ISSUE TITLE
Inconsistent allowed child types on custom type contents

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sensenet#1608]
the error is similar or the same as #1607, but from admin ui
it occurs when the CTD is named explicitly as "Page", so the edited repro steps accordingly

Process and error message:
- create 3 CTDs: MyTypeA, Page, MyTypeC
- MyTypeA CTD allowed child types contains Page
- Page CTD allowed child types contains MyTypeC
- allow MyTypeA child type on /Root/Content
- create MyTypeA content under /Root/Content
- create Page type content under /Root/Content/MyTypeA
- try to create MyTypeC type content under Page type content

you will see that under the Page type content you only see content types allowed on MyTypeA ctd instead MyTypeC which we set as allowed child type

**Comment by tusmester** [comment]
Could not reproduce this, need more info. 
- admin ui or client code?
- User: who created the ctds, who created the content items?
- what are the allowed child types values in the ctds?

**Comment by VargaJoe** [comment]
the error is similar or the same as 1607, but from admin ui
it occurs when the CTD is named explicitly as "Page", so the edited repro steps accordingly

Process and error message:
- create 3 CTDs: MyTypeA, Page, MyTypeC
- MyTypeA CTD allowed child types contains Page
- Page CTD allowed child types contains MyTypeC
- allow MyTypeA child type on /Root/Content
- create MyTypeA content under /Root/Content
- create Page type content under /Root/Content/MyTypeA
- try to create MyTypeC type content under Page type content

you will see that under the Page type content you only see content types allowed on MyTypeA ctd instead MyTypeC which we set as allowed child type

**Comment by kavics** [comment]
This is not a bug, but a feature. In enabling the child type feature, the "Page" content type, behaves in a transitive way, like the "Folder" content type. See the new acceptance tests:
- AllowedChildTypes_Bug1607_Transitive_Page: reproduction test for these issues.
- AllowedChildTypes_Bug1607_Transitive_Folder: transcript of the previous test, where "page" was replaced by "folder".

**Comment by tusmester** [comment]
Developers will get an error when trying to define allowed child types on a transitive CTD. #1729
