### ISSUE TITLE
Node load sorting fails when the results come from only db (not cache)

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#162]
In that rare case when a set of node heads are **not in cache** (none of them!), the _DataBackingStore.GetNodeHeads_ method fails to preserve the original order.

https://github.com/SenseNet/sensenet/blob/aa31792ae03ee53a1213b8cdc68197dbad544471/src/Storage/DataBackingStore.cs#L97

If in the method above all loaded heads go to the _unloadHeads_ collection (the _nodeHeads_ collection remains empty), **sorting is switched off** (probably for performance reasons). In this case the result list will contain ids in the raw db order, instead of the original, sorted order.

### Solution
_Maybe_ the solution is to remove the condition and sort the result list always.

**Comment by kavics** [comment]
This bug blocks any unit test that use sorting.

**Comment by tusmester** [comment]
@kavics please connect this to the closed pr and move it to the done column, I checked the code, it's ok.

**Comment by tusmester** [comment]
Fixed by #163
