### ISSUE TITLE
Let's retire Luke (save index to human readable format.)

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#1686]
Extend all Search or Indexing engines with saving index capability. The saved material needs to be human-readable to help discover the existing index and index document structure and to help investigate any problems.

Implement the future solution for:
- [ ] In memory index
- [ ] Lucene index

Also add an **odata operation** for requesting individual index documents: `GetIndexDocument`
(required because in many cases we do not have access to the db or file system)

**Comment by tusmester** [comment]
Added the requirement for an odata action.
