### ISSUE TITLE
Gmail '+' dynamic email feature breaks assign repository

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sensenet#1737]
When a user registers with an email alias or task specific email address of google, so the email address has a "+" (plus) sign in it, the terms of use step breaks the process.

`Copy Terms Of Use failed - Assign Repository operation is aborted`

Backend throws a "System.InvalidOperationException: Copy failed: target content does not exist with path" exception in AssignRepositoryActivity.cs 

Plus sign is a special character, so it is replaced in content paths.

The user get an "Your sensenet repository is ready" and can log in.

**Comment by kavics** [comment]
Related PR in the TFS:
https://tfs.sensenet.com/SenseNetProductTeam/SenseNet/_git/snaas-services/pullrequest/237
