### ISSUE TITLE
[UX] Browser shortcut for logging in to a repository with admin ui

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#1752]
Pls check if this is already available!
I'd like to have a **browser shortcut** for logging in to a specific repository. This would require the AdminUI application to be able to handle a **target repository query parameter**:

https://admin.test.sensenet.com?repoUrl=inmem-daily.test.sensenet.cloud

- parameter name: `repoUrl`
- precedence: if the user is already logged in to a different repository (according to a browser cookie or local storage), we have to switch to the one provided in the url
- ~https is not necessary, default is https~ moved to https://github.com/SenseNet/sn-client/issues/1428

**Comment by VargaJoe** [comment]
currently we can use `repoUrl` query parameter with encoded repository url
