### ISSUE TITLE
[UX] Customize the File details page

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#1766]
Currently it looks like the File details (browse) page is assembled automatically, based on the CTD. If possible, customize it to be more informative:

- hide the Binary field with filename, display a **Download** action button instead (if the action is available!)
- the Filename field should be displayed first, prominently
- Page count: 
    - if the value is > -1, display it
    - otherwise display the appropriate state information (error, not generated, ....)
- Display creation date?
- The **Modification Date** field should be adaptive time display same way as in the grid: Just now, Yesterday, etc. The full date text should be a **tooltip**.
- Display **checkout** (locked by) information (same as the lock icon in the grid)
- display all other **dynamic fields** coming from the ctd below the manual ones
- Cancel button should be **Close**

![image.png](https://images.zenhubusercontent.com/58e4d2b951aa2c30577a6fb6/c3ac3e83-ef37-4137-9ba9-27f0fa790b4e)

**Comment by tusmester** [comment]
All the topics above have been moved to individual issues in the Admin UI enhancements epic.
