### ISSUE TITLE
[UX] Inactive notification button

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#1767]
There is a bell on the top right corner that does nothing.
![image.png](https://images.zenhubusercontent.com/58e4d2b951aa2c30577a6fb6/ae3f4ecb-3b67-4d2b-bbec-d0ac54315396)

If there is no data to show:
- disappear the bell or
- show a tooltip or small window: "There is no data to show" or something like this.

**Comment by tusmester** [comment]
Already done.
