### ISSUE TITLE
sn-io import fails with public admin client

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sensenet#1861]
sn-io import gets forbidden error whit PublicAdmin client settings
![image.png](https://images.zenhubusercontent.com/58e7cc3451aa2c30577ab29c/1dcf51a0-032e-44f5-83e6-6178004347b7)

repro:
- log in to daily test: https://daily.test.sensenet.cloud
- get an access token
- set your sn-io for import
- try it out

**Comment by tusmester** [comment]
The Import action access issue has been solved. There is another permission-related issue when importing with public admin (see-only permission for the Root) but that is a separate issue.
