### ISSUE TITLE
Permission error when importing with public admin

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#1867]
When we try to import **files** to https://daily.test.sensenet.cloud in the name of the public admin user, we receive a permission error:

```
Invalid property access attempt on a See-only node: /Root
```
This is caused by the `Folder.IsPreviewEnabled` property that tries to **access the parent**. 

```csharp
public virtual bool IsPreviewEnabled => Parent?.IsPreviewEnabled ?? false;
```

Check and solve this (probably with **elevation**) in one or both of the following places:
- Folder class
- Node class

Add **property name** info to the trace message above.

**Comment by kavics** [comment]
The merged modification does not fix the basic problem.
See also: #1861
