### ISSUE TITLE
Disposed object exception with a previously successfully imported package

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sensenet#1933]
An import error is occured when attempting to import a package that had been successfully imported in the past. However, the issue is not consistently reproducible, as the import process functions flawlessly after removing the previously imported content. 

![image.png](https://images.zenhubusercontent.com/58e7cc3451aa2c30577ab29c/63db287c-998b-45a6-b567-0d2e23432af4)

**Comment by tusmester** [comment]
Issue moved to [SenseNet/sn-io #38](https://github.com/SenseNet/sn-io/issues/38) via [**Zenhub**](https://www.zenhub.com/)
