### ISSUE TITLE
Despite generating previews for image-type files (e.g., PNG), the log is filled with DocumentPreviewFinalizer errors

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sensenet#1935]
Even though previews are successfully generated for image-type files (such as PNG), the log files are consistently filled with DocumentPreviewFinalizer errors. 

HTTP "POST" "/odata.svc/Root/Content/SampleWorkspace/ImageLibrary('lemur-5442927_640.jpg')/DocumentPreviewFinalizer" responded 500 in 3.5022 ms

**Comment by tusmester** [comment]
This may have been a config error due to auth changes. Check this after the release.
