### ISSUE TITLE
[BUG] There is no option for ignoring fields when save registered typed content in sensenet client 3.0

### ISSUE THREAD

**Issue by HegyiOliver** [SenseNet/sensenet#1946]
![image](https://github.com/SenseNet/sensenet/assets/115475477/ef0230b1-d641-4e00-abc1-8d3b9adea4a1)

This exception was originally thrown at this call stack:
    System.Array.SetValue(object, int)
    SenseNet.Client.Content.GetMultiReferenceArray(object, System.Type)
    SenseNet.Client.Content.MultiReferenceIsChanged(object, string, Newtonsoft.Json.Linq.JToken, System.Type)
    SenseNet.Client.Content.ManageReferences(System.Type, string, object, Newtonsoft.Json.Linq.JToken, System.Collections.Generic.IDictionary<string, object>)
    SenseNet.Client.Content.ManagePostData(System.Collections.Generic.IDictionary<string, object>)
    SenseNet.Client.Content.SaveAsync(System.Threading.CancellationToken)
    
    This is caused by a helper property that is not defined in the CTD. It is created to access some data easier and supposed to be a transient / not mapped field. 
![image](https://github.com/SenseNet/sensenet/assets/115475477/bb18d3cc-e5a6-49c6-a21f-b7672f8a7423)

**Comment by kavics** [comment]
I need to know the error message.
