### ISSUE TITLE
Error Occurs on Previously Created Content After Deleting Fields from CTD

### ISSUE THREAD

**Issue by VargaJoe** [SenseNet/sensenet#2042]
Following the deletion of fields from a Content Type Definition (CTD), the system encounters an error when attempting to access previously created content associated with the modified CTD. This issue disrupts the functionality of the affected content.

<img width="612" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjA0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5f336b00d76bd1f5cb912b462db9a277f88a403/image.png" alt="image.png" />

**SOLUTION**
1 - Skip these errors
2 - Probably remove the deleted field data with a maintenance task because of GDPR.

**Comment by marosvolgyiz** [comment]
nem volt graylog, lezárjuk, ha előjön felvesszük újra
