### ISSUE TITLE
Too many apikeys generated for task user.

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#2069]
Every system start sequence generates 2 api-keys even if they are not expired.

**Comment by tusmester** [comment]
The "task executor to repo" authentication is configurable. See:
- https://github.com/SenseNet/sn-taskmanagement/blob/master/src/TaskManagement.Core/TaskManagementOptions.cs
- https://github.com/SenseNet/sensenet/blob/master/src/WebApps/SnWebApplication.Api.Sql.TokenAuth.Preview/Properties/launchSettings.json

The docs is not clear on this unfortunately:
- https://docs.test.sensenet.com/api-docs/configuration/taskmanagement/TaskManagementOptions
