### ISSUE TITLE
Log level could be lower

### ISSUE THREAD

**Issue by HegyiOliver** [SenseNet/sensenet#2101]
## Description

There are some cases in the code where log level is set to error, but it would be enough warning or information 

## Stacktrace

Timestamp: 2024. 04. 17. 14:07:18 Message: Cannot save the content ... because its ancestor does not allow the type ... Ancestor: ... Allowed types: ...  Category: General Priority: -1 EventId: 1 Severity: Error Title: Machine:... Application Domain: ... Process Id: ... Process Name: ... Managed Thread Id: ... Thread Name: .NET ThreadPool Worker Extended Properties: Messages - InvalidOperationException: at SenseNet.ContentRepository.GenericContent.AssertAllowedChildType(Node node, Boolean move) at SenseNet.ContentRepository.SavingAction.ExecuteAsync(CancellationToken cancel) at SenseNet.ContentRepository.GenericContent.SaveAsync(SavingMode mode, CancellationToken cancel) at SenseNet.ContentRepository.GenericContent.SaveAsync(CancellationToken cancel) at SenseNet.ContentRepository.Storage.Node.DoCopyAndGetCopy(String targetPath, String newName) at SenseNet.ContentRepository.Storage.Node.CopyToAndGetCopy(Node target, String newName) at SenseNet.Services.Core.Operations.ContentOperations.CopyBatch(Content content, String targetPath, Object[] paths) =====================

**Comment by marosvolgyiz** [comment]
Ez tipikusan error jellegű bejegyzés. Szóval maradjon error. A jegyet lezárom.
