### ISSUE TITLE
SPIKE: IdentityServer kiváltása asp.net-el

### ISSUE THREAD

**Issue by marosvolgyiz** [SenseNet/sensenet#2103]
TODO: 
- asp.net webapp-ban váltsuk ki
- mit tud most az identity server? 
-- login
-- regisztráció
-- multifactor
-- elfelejtett jelszó
- mennyire secure, hogy 1 szereplős a bejelentkezés? 
- meg lehet-e csinálni és kb. mennyi meló?

**Comment by hashtagnulla** [comment]
Mit tud most az identity server?
- Nagyjából a felsoroltak a fő funkciói, amit érdemes még megemlíteni az a third party login/regisztráció

Mennyire secure, hogy 1 szereplős a bejelentkezés?
- Jó autentikációs/autorizációs implementációval ez is elegendő lehet és biztonságos, de a már kialakított multifaktoros auth-ot is fel lehet használni.

Meg lehet-e csinálni és kb. mennyi meló?
- Konkrét tervek után (folyamatábra stb.) szerintem 1-1,5 hét max.
