### ISSUE TITLE
WebDAV and Open in Office does not work

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#214]
WebDAV and Open in Office does not work in the latest release.
This may be related to #213 , but these features should work with Forms auth too so...
 
Acceptance criterias:
- [ ] ~~network drive mapping works~~
- [x] webdav office editing works
- [x] preflight request works
- [x] space in url editing scenario works

**Comment by tusmester** [comment]
We'll release a patch in a day or two that addresses webdav and windows auth issues. We shall see if that solves these problems.

**Comment by swacsa** [comment]
I've tried it on the daily demo site - which have 7.0.1 services pack - but I have some bug while tried to open the file: http://bit.ly/2BLS1C9
