### ISSUE TITLE
Open in office Activity tab does not work if there is a space in the name of the workspace

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#218]
Fix and backport to SN6 release branch.

## Acceptance criteria
- [x] It works in sn6 and sn7 as well
- [x] notify the CF team

**Comment by tusmester** [comment]
I compared a correct and an incorrect session (list of requests) in Fiddler. The actions were the following:

- open a file in Word
- switch to Edit mode
- open the _Actions_ panel (icon in the top right corner, above the ribbon)

Results: the two request/response lists were identical, except that in the correct case there was a request for the **versions.asmx** at the end that returned the correct versions list. 

Server-side code: _Portal_ project (in sn6) or _Services_ project (in sn7), Dws folder, _VersionsHandler_ class.

It seems that Word simply does not send a request for the version list if there is a space in the workspace name.

Note: it does not seem to be a problem if there is a space in the name of the doclib, so **this is not a 'space in the path' problem**, which I thought it was.

**Comment by iviczl** [comment]
Even the open in Edit Mode was a problem in sn7, but @kavics found two different bugs and their solution that have been affecting the behaviour of MS Word.

**Comment by iviczl** [comment]
It looks like the "space in the path" in _vti_bin/shtml.dll/_vti_rpc WebDAV call's weburl output parameter affects the activity calls later.

**Comment by tusmester** [comment]
The path manipulation logic has been simplified and this makes opening and editing files in Word possible (when you open the file from the web).

Mounting the repo as a drive in Windows Explorer still has some issues in SN7, but that is another issue. This fix has been backported to SN6.
