### ISSUE TITLE
odata query filtering bug

### ISSUE THREAD

**Issue by Khegyi** [SenseNet/sensenet#22]
Hi!
I could not filter a reference field's attribute e.g. I wanted to get all the workspaces, which was modified by a specific user:
 "https://demo06.demo.sensenet.com/OData.svc/workspaces?metadata=no&$filter=ModifiedBy/Name%20eq%20%27Admin%27"

**Comment by kavics** [comment]
OData filtering is totally off because result is empty if the filter is **ModifiedById eq 1** or **ne 1** or **lt 2**

**Comment by kavics** [comment]
Filter by an expanded property is not supported in this version.

**Comment by tusmester** [comment]
We may revisit this in the future as a feature request.
