### ISSUE TITLE
es6+ / Typescript

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sensenet#222]
## Training Goal

 - Learn basic Typescript concepts. Update an NPM package to use Typescript.

## Prerequisites
 - NPM package from the previous lesson

## Steps
 - Installing Typescript
 - Update the project to use with Typescript
 - Basic concepts
    - Type annotations
    - Interface definition
    - Enums
    - String literals
    - Classes
    - Callback types
    - Modules, imports, exports
    - Documentation
    - Advanced types
          - Intersection types
          - Union types
          - Type guards ( & duck typing)
          - Generics
          - Type aliases

## Related video tutorials
https://egghead.io/courses/learn-es6-ecmascript-2015
https://www.typescriptlang.org/docs/handbook/basic-types.html
https://egghead.io/courses/use-types-effectively-in-typescript

**Comment by tusmester** [comment]
Closed as obsolete.
