### ISSUE TITLE
Port documentation from wiki: Content and Node

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#238]
Port old articles from wiki and refresh them for **sensenet 7**. We may combine or separate them as needed.
The new article should be an .md file in the sensenet repository's _/docs_ folder. Old screenshots should be remaked on the new [admin-ui](https://admin.sensenet.com) if it is possible and placed into the _/docs/images_ folder.

- [ ] Node - GenericContent - Content
   - [ ] [Content - for developers](http://wiki.sensenet.com/Content_-_for_Developers)
   - [ ] [Node - for developers](http://wiki.sensenet.com/Node_-_for_Developers)
   - [ ] [GenericContent - for developers](http://wiki.sensenet.com/GenericContent_-_for_Developers)

**Comment by bvishal8510** [comment]
@tusmester, May I do this?

**Comment by bvishal8510** [comment]
@herflis, a single file is needed to be created for each topic or they all should be contained within single file?

**Comment by herflis** [comment]
Hey @bvishal8510 ,
pls create a file for each of the topics. Thank you for your help! 🙏

**Comment by Attila816** [comment]
hello Aniko, what is the status of this?
can I work on it?

**Comment by bvishal8510** [comment]
@Attila816 I am working on it.

**Comment by parammittal16** [comment]
@bvishal8510 @tusmester I have made the file for Node - for developers.
