### ISSUE TITLE
'New' scenario returns only the 'File creator' actions through odata

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#248]
On the old admin surface if I open the 'New' action menu in a user profiles doclib the followings are listed:
- Empty document.docx
- Empty presentation.pptx
- Empty text document.txt
- Empty workbook.xslx
- Folder
- Smart Folder
- and only for admin users System Folder

![newmenu](https://user-images.githubusercontent.com/6968860/34941645-e44f1e44-f9f4-11e7-922f-541f3e79ce66.png)

So the list above is the expected response of a /Action?scenario=New request.

But if you send a /Actions?scenario=New request on the same doclib through OData only the followings are in the response:
- Empty document.docx
- Empty presentation.pptx
- Empty text document.txt
- Empty workbook.xslx

[link](https://dmsservice.demo.sensenet.com/odata.svc/content(4490)/Actions?scenario=New&metadata=no&$inlinecount=allpages)

**Comment by tusmester** [comment]
I've checked on two test sites, it seems to be working now.

**Comment by herflis** [comment]
It is permission related. Only the administrator (and the developers group) has see permission on the Fodler ContentType for example. So pls modify the backend script which allows or denies things in the import/install process

**Comment by tusmester** [comment]
Added See permission for the IdentifiedUsers group to the Folder type (the same way as it is on the File type), this solves the issue for now. Later we should rethink initial permissions, maybe allow a few more things to _Everyone_.
