### ISSUE TITLE
Actions menu does not work on Content Types

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#264]
When in Content Explorer (or an OData call from the client) I try to open the **Actions menu** (on the toolbar above the grid) **on a content type**, I receive the following error:

> Unknown action. Action: SmartAppGetActions

Reason: the necessary action is defined for the GenericContent items, but not for content types.

### Solution
Copy the action above from the _/Root/(apps)/GenericContent_ folder to the _/Root/(apps)/ContentType_ folder so that it becomes available to content types as well.

**Comment by jeremie1112** [comment]
Can you assign this to me. And could you give me more details how to reproduce the above error as I am a beginner and wants to contribute. @tusmester
