### ISSUE TITLE
Review unimplemented permission query parameters

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sensenet#275]
There are some permission action parameters that (based on some code comments) seems to be unimplemented for a while. Based on the generated client code, they are required for action calls. We should talk about cleaning up this API by removing these or at least making them optional with a default parameter.

The actions and their parameters are the following:

**GetRelatedIdentities**
 - level - The value is "AllowedOrDenied". "Allowed" or "Denied" are not implemented yet.

**GetRelatedPermissions**
 - level - The value is "AllowedOrDenied". "Allowed" or "Denied" are not implemented yet
 - explicitOnly - The value "true" is required because "false" is not implemented yet.

**GetRelatedItems**
 - level - The value is "AllowedOrDenied". "Allowed" or "Denied" are not implemented yet
 - explicitOnly - The value "true" is required because "false" is not implemented yet.

**GetRelatedIdentitiesByPermissions**
 - level - The value is "AllowedOrDenied". "Allowed" or "Denied" are not implemented yet

**GetRelatedItemsOneLevel**
 - level - The value is "AllowedOrDenied". "Allowed" or "Denied" are not implemented yet

**Comment by tusmester** [comment]
+1 for the optional parameter solution. It may require some backend effort to make **OData functions accept optional parameters**. Full action classes are capable of this now, but simple OData methods are not - yet.

**Comment by gallayl** [comment]
We've deicided not to change the API until we're requested to do so.
The docs are up to date in the related [wiki](http://wiki.sensenet.com/Permission_queries) page and in the [@sensenet/client-core](https://github.com/SenseNet/sn-client-core/blob/master/src/Repository/Security.ts) package
