### ISSUE TITLE
Port documentation from wiki: Content query API

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#280]
Port old articles from wiki and refresh them for sensenet 7. The new article should be an .md file in the sensenet repository's _/docs_ folder. Old screenshots should be remaked on the new [admin-ui](https://admin.sensenet.com) if it is possible and placed into the _/docs/images_ folder.

- [ ] [Content Query API](http://wiki.sensenet.com/Content_Query_API)

**Comment by gagandeepp** [comment]
@herflis  Assigned this to me

**Comment by gagandeepp** [comment]
Please review and merge

**Comment by herflis** [comment]
@gagandeepp pls fix your pull request because now it is made in the wrong repository

![image](https://user-images.githubusercontent.com/6968860/66388895-62641280-e9c7-11e9-8e16-70be9f44a7da.png)
