### ISSUE TITLE
Collect SN6-SN7 patch info

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#304]
Compare a sensenet 6.5 and a full sensenet 7 instance and start creating manifest fragments. This is a **timeboxed SPIKE** for collecting the first steps.

**Log the work** to prepare for the blog post at the end.

- [ ] ~collect content to remove: Nodes table~
- [x] db changes
   - [x] schema update script
   - [x] stored procedure script
- [x] CTD changes
   - [x] update analyzer step
   - [x] compare all ctd xmls
- [x] libraries to delete during patch

**Comment by kavics** [comment]
Please review these:
- 8 SQL script created for the upgrading schema: P:\....\patch\65to71\sql-schema\\*.sql
- CTD existence diff: P:\....\patch\65to71\CTD\Names-DIFF.txt
- CTD content diff: P:\....\patch\65to71\CTD\CTD-DIFF.txt
