### ISSUE TITLE
Uppercase site URL

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#311]
It is not possible to assign a url containing **uppercase letters** to a sensenet site (for example www.SomeTestUrl.com).

The problem is most likely in the _Site.IsValidSiteUrl_ method: the _uri.Authority_ property check fails in this case.

- [x] fix ~and notify TC~
- [x] add a test

**Comment by atomanonymous** [comment]
I'll work on this!

**Comment by atomanonymous** [comment]
some help needed here where do i find the particular file?

**Comment by tusmester** [comment]
@atomanonymous 
https://github.com/SenseNet/sensenet/blob/178ed365d4c66ef51f4942aa603142f3497a3ec2/src/Services/Site.cs#L228

**Comment by berry120** [comment]
Hello, notice this one is unassigned, but looks like it may be complete already (or is there still more work to do here?)

**Comment by B3zo0** [comment]
Hi @berry120 this is already fixed in #693 . We usually close issues that are released and this is not yet released.
