### ISSUE TITLE
Identity management documentation is missing

### ISSUE THREAD

**Issue by swacsa** [SenseNet/sensenet#323]
Identity management configuration documentation is missing from the new community site, we should **port the existing docs** from the old wiki, add missing sections and links to other related articles (e.g. _ad sync_).

- [ ] User profiles
   - what are they
   - how, when and where are they created
   - configuration

http://wiki.sensenet.com/User_Profile
http://wiki.sensenet.com/User_Content_Type

- [ ] Default domain
It is possible to set the default domain of the login process using the DefaultDomain tag. This way users can login with their user names without using the "domain" prefix. 

```xml
<identityManagement>
    <add key="DefaultDomain" value="domain" />
</identityManagement>
```

- [ ] create new issues for missing related docs (e.g. permission system?)

**Comment by tusmester** [comment]
@swacsa if you want to add the missing config, please fork the sensenet repo and send a pull request to the new docs/identitymanagement branch that contains the sceleton of the new doc file (_/docs/identity-management.md_).

**Comment by Niladri24dutta** [comment]
@tusmester I would like to work on this. Where should I add missing documentation links?
