### ISSUE TITLE
ContentQuery LINQ StartsWith issue

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#348]
By @VargaJoe

```csharp
var crmcontactsall = this.Model.Items.Where(c => c.Type("RorWebCRMContact") && c.Path.StartsWith(company.Path)).ToList();
```

This worked in 7.0.2, but after upgrading to 7.1.1 it gives _0 results_ without an error. If we replace the 'startswith' term with 'InTree' (which is the recommended way anyway) it works correctly.

```csharp
var crmcontactsall = this.Model.Items.Where(c => c.Type("RorWebCRMContact") && c.InTree(company.Path)).ToList();
```

@kavics: Has something changed related to this feature in the last few releases? Should this work?
@VargaJoe: please clarify the type of _Model.Items_, is that a list in a collection view (ascx)?

**Comment by VargaJoe** [comment]
yes, the example code is from a ContentCollectionView

**Comment by kavics** [comment]
I cannot reproduce this bug so I would like to see/debug the actual solution. The _ContentCollectionView.Model_ is a _ContentCollectionViewModel_ (what a surprise). This object is generally an IQueryable<Content> that can wrap IEnumerable<Content> or ISnQueryable<Content>. This duality maybe can cause an error but I think this is not the case now.

**Comment by VargaJoe** [comment]
I've managed to reproduce the bug with the following steps:
- installed services and webpages with snadmin 
- changed the contentcollectionview to insert a few extra rows
  ```
var test = this.Model.Items.Where(c => c.Type("Page") && c.Path.StartsWith("/Root/Sites/Default_Site")).ToList();
var test2 = this.Model.Items.Where(c => c.Type("Page") && c.InTree("/Root/Sites/Default_Site")).ToList();
```
and duplicate the foreach to use these lists
- created a page with a ContentCollectionportlet and set to query all the page with CurrentSite bindings and use the modified view
(interestingly, when I set CustomRoot with /Root or /Root/Sites, the portlet does not give results, but with CustomRoot /Root/Sites/Default_Site does)
- on the test page the first foreach shows nothing and the second shows the two pages (login and the test page)

I could try to reproduce this on a demo site if there is any.

Components:
SenseNet.Services | 7.1.1 | 7.1.1 | sensenet Services
SenseNet.WebPages | 7.1.0 | 7.1.0 | sensenet ECM WebPages

Installed Packages:
1 | SenseNet.Services | sensenet Services | Install | 04/02/2018 | 05/02/2018 | 0 | 7.1.1 |   |  
2 | SenseNet.WebPages | sensenet ECM WebPages | Install | 04/05/2017 | 05/02/2018 | 0 | 7.1.0 |   |
