### ISSUE TITLE
Odata query returns misleading _count property when the query is translated to SQL query instead of Lucene query for performance optimization

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#35]
When an Odata query can be translated to SQL query for faster execution the __count property always shows the invalid value. Actually it shows the filtered result count with skip, top because the SQL query cotains them and there is no second query for a count only execution. 

## Acceptance criteria
- [x] Fix the bug in SN70Beta
- [x] Fix the bug in SN 6.5.4 in a hotfix branch
- [x] Report back in JIRA

**Comment by iviczl** [comment]
Altered the executor selection by signaling not compilable for sql executor in case of inlinecount=allpages.
