### ISSUE TITLE
Heavy exceptions are not logged to eventlog

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#36]
There are various message length limit that depends on the OS. https://support.microsoft.com/en-us/kb/957662
If we are trying to log an exception which is bigger that this then it is not logged at all.

### Example:
var props = Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string, object>>(System.IO.File.ReadAllText(@"C:\temp\long exception.txt"), new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.All });
Microsoft.Practices.EnterpriseLibrary.Logging.Logger.Write(ex.Message, new List<string>(), -1, 666, TraceEventType.Error, string.Empty, props);

### This works:
var props = Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string, object>>(System.IO.File.ReadAllText(@"C:\temp\long exception.txt"), new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.All });
props.Remove("ContentRegistrationException/OldAspectDefinition");
Microsoft.Practices.EnterpriseLibrary.Logging.Logger.Write(ex.Message, new List<string>(), -1, 666, TraceEventType.Error, string.Empty, props);

## Acceptance criteria
- [ ] Fixed in SN70Beta
- [ ] Fixed in SN 6.5.4
- [ ] Reported back to JIRA

**Comment by tusmester** [comment]
closed as obsolete
