### ISSUE TITLE
Sensenet 6.5.X web deployment package not available

### ISSUE THREAD

**Issue by purplemana** [SenseNet/sensenet#425]
All the links in https://archive.codeplex.com/?p=sensenet are dead. Anywhere else? Or has 6.5 been sunset?

**Comment by kultsar** [comment]
Hi purplemana, yes, 6.5 is deprecated. Sensenet 7 is the recommended way to go: https://community.sensenet.com/docs/install-sn-from-nuget/

**Comment by purplemana** [comment]
Thanks for the update.
