### ISSUE TITLE
Custom OData action for getting children by ID

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sensenet#426]
URL example /OData.svc/content(42)/children
 - [x] Create a custom OData function that returns a collection of a content's children
 - [x] The available OData options and the response should be the same as for the **collection url** of the same content
Related PR: https://github.com/SenseNet/sensenet/pull/429
---
Autofilters and lifespan filters are not working as expected at the moment - related issue: https://github.com/SenseNet/sensenet/issues/428

**Comment by tusmester** [comment]
@gallayl pls review.

**Comment by gallayl** [comment]
- If I **$expand** the Children reference, I've got all repository content in the response (```/odata.svc/('Root')?$expand=Children```). I think it should work with in an **InFolder** mode, the expanded field should reflect the same content collection as ``/odata.svc/('Root')/Children``
 - However I can **$select** fields when calling ```/odata.svc/('Root')?$expand=Children&$select=Chilrden/Path```, I cannot **$select** fields when I expand the Children reference, e.g. the following request throws an 500 error ```/odata.svc/('Root')?$expand=Children&$select=Chilrden/Path```)
The response:
```json
{
  "error": {
    "code": "InvalidSelectParameter",
    "exceptiontype": "ODataException",
    "message": {
      "lang": "en-us",
      "value": "Bad item in $select: Chilrden/Path"
    },
    "innererror": null
  }
}
```
I think if the following problems cannot be solved in an easy way, we should deny expanding the Children reference for now, the action works fine in a separate request
