### ISSUE TITLE
Provide Version properties related to creation/modification

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#442]
Now it is not possible to get the followings of a Version:
`CreationDate`
`ModificationDate`
`CreatedBy`
`ModifiedBy`
Since it is on the ui as a column of the version history, we need them in the OData response of a '/Versions' request in the near future.

**Comment by kavics** [comment]
The CTD of the GenericContent is extended by four fields based on the existing server-side properties with the same name:
- VersionCreatedBy
- VersionCreationDate
- VersionModifiedBy
- VersionModificationDate

These fields can be tested with a specific URL like this:
http://____.__/odata.svc/Root/Sites/Default_Site/DocLib('BusinessPlan.docx')?metadata=no
&$expand=Versions,CreatedBy,ModifiedBy,Versions/VersionCreatedBy,Versions/VersionModifiedBy
&$select=Name,CreationDate,CreatedBy/LoginName,ModificationDate,ModifiedBy/LoginName
,Versions/Version
,Versions/VersionCreationDate
,Versions/VersionCreatedBy/LoginName
,Versions/VersionModificationDate
,Versions/VersionModifiedBy/LoginName
