### ISSUE TITLE
[DMS] Share GUI

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sensenet#448]
![image.png](https://images.zenhubusercontent.com/58e4b9a551aa2c30577a6d94/7cfa4cdf-181d-43e5-bca2-0c4583a4cf9d)

 - [x] Implement the document sharing GUI for the DMS Demo
 - [x] The modal window should be available from the context menu and from the batch actions menu
 - [x] Input should be required
 - [x] A console message should appear on post with the payload data and the modal should be closed

**Comment by kultsar** [comment]
When initiated from batch actions on multiple items, the modal currently shows the name of the current folder, and user might think that the sharing will apply to it:
![image.png](https://images.zenhubusercontent.com/5af2e69b4b5806bc2bd27313/c85ade04-8bf1-417a-820f-f8d03e39c8b3)
We should change this. Suggestion: write "multiple items" to the place where we normally write the name of the file/folder to share, in parentheses and italics: *(multiple items)*. Or, we could change the title of the modal from "Share" to " Share multiple items", and write nothing as the name of the item in the window.

**Comment by gallayl** [comment]
the console.log message object should be customized when we agree the payload format for the Share custom action (see https://github.com/SenseNet/sensenet/issues/449)

**Comment by kultsar** [comment]
Issue moved to [SenseNet/sn-dms-demo #418](https://github.com/SenseNet/sn-dms-demo/issues/418) via [**ZenHub**](https://www.zenhub.com/)
