### ISSUE TITLE
Content sharing

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sensenet#449]
The result of the latest UX Research:

![image.png](https://images.zenhubusercontent.com/58e4b9a551aa2c30577a6d94/ff2bb503-e4e1-43ec-a493-43db1f4b7cbe)

This is how we currently plan to create the sharing feature in sensenet.

### Entry point
- Sharing starts on a content. 
- Display a list of previous sharing records with _Delete_ option.
- Sharing **modes**
   - anyone with the link: even visitors, no authentication required
   - authenticated users only (anyone signed in: the _Everyone_ group)
   - specific persons: identified by **e-mail address**, requiring authentication
- Access **levels** for now
   - view content
   - edit content

### Managing sharing on the client
We will create **custom actions** for getting/setting sharing data, accessible only for certain groups.
##### Question: action access (who can share a content?)
This can be strict for now, later we may lower the bar - for example let target users share it further.
> - users with _SetPermission_ rights on the content?
> - only the _Owner_ of the document?
> - ~members of a certain group/role?~

### Sharing data
The stored data is **filtered** when sent to the client, only info accessible for the current user is provided.
- token (email, random word)
- identity (user/group id or Somebody)
- mode (public/authorized/private)
- level (open/edit/...)
- who shared it (or Somebody)
- when was it shared
- ~expiration date~

### Example payload for client actions
```json
{
  "d": {
    "__count": 2,
    "results": [
      {
        "Id": "42d187a1-c2a7-4820-83cc-9127433f1eba",
        "Token": "abc1@example.com",
        "Identity": 123,
        "Mode": "Private",
        "Level": "Open",
        "CreatorId": 1,
        "ShareDate": "2018-10-18T10:04:14.7924455Z"
      },
      {
        "Id": "6ad87747-8354-41e6-a263-600a0adf81f5",
        "Token": "abc2@example.com",
        "Identity": 8,
        "Mode": "Authenticated",
        "Level": "Edit",
        "CreatorId": 42,
        "ShareDate": "2018-10-18T10:08:54.2348904Z"
      }
    ]
  }
}
```

### Sharing storage and management
- sharing info is **stored on the target content** in a new **strongly typed sharing info property** stored as longtext
- new fake field for _indexing_ and _exporting/importing_ sharing info (_not_ 'based on the property')
   - the field is hidden, it does not contain and expose the raw data!
   - export/import is allowed for admins only, id<-->path conversion is necessary
   - later: export partial sharing info, without dates and 'user who shared' info
- query: fake field index handler creates index terms

### Hooks for changes
- user email changes
- user is deleted
- ???

**Comment by gallayl** [comment]
Update: We've agreed to modify the specs for the Share function and work only with e-mail addresses.

**Comment by tusmester** [comment]
Why are we excluding usernames, full names or any other field that can be used to identify existing users?

**Comment by kultsar** [comment]
For existing users, in my opinion, any fields that uniquely identify them, could be fine. E-mail addresses, usernames, etc. Full names do not uniquely identify them, I guess.

**Comment by gallayl** [comment]
Consider the following scenarios:

1. The user who want to share the doc doesn't have permission to actual *user content* and *should not know* if a user is already registered with that name
1. The user is not registered yet, but you want to share the doc with her. Maybe you have to create a *temporary / placeholder* user and notify her. If she completes her registration (e.g. with Google OAUTH) we should be able to correlate with an unique key in an authorized way.
1. There can be multiple users registered with the same full name / display name

We should talk about how we threat the login name / email address relationship. We use email addresses as login names in the DMS Demo at the moment to ensure the uniqueness within the public domain.

We've agreed that we can implement a contact list (private, workspace-bound or whatever) and use it to *pick* users for sharing in a later version.

**Comment by tusmester** [comment]
Sorry, when I said _identifying_ users I meant only on the sharing GUI :). I was referring to how I (as the document owner) can search for users when sharing: by email, or by username/fullname. Of course this should only show me users that I have access to.

If you do not have access to an existing user but you provide his email address, that can be handled in the background, the client should not know anything about how we store sharing info.

**Comment by kultsar** [comment]
Access types for now:
* view content
* edit content

Share types:
* anyone with the link: visitor, no authentication required
* specific persons: identified by e-mail address of a registered user, requiring authentication

URL contains no human-readable data (nothing about content or user data should be inferred)
Separate URL is generated based on GUIDs generated for each shared content and access type and share type combination. At present this can mean:
- 1 GUID/URL for visitors with view access
- 1 GUID/URL for visitors with edit access
- 1 GUID/URL for identified users with view access
- 1 GUID/URL for identified users with edit access

**Comment by tusmester** [comment]
##### Discussion memo
- security component is almost ready (permission category feature), except _permission queries_
- sharing record is **stored on the target content** in a new longtext storage property
- new fake field for _indexing_ and _exporting/importing_ sharing info (_not_ 'based on the property')
   - the field is hidden, it does not contain the raw data!
   - export/import is allowed for admins only, id<-->path conversion is necessary
   - later: export partial sharing info, without dates and 'user who shared' info
- query: fake field index handler creates index terms
