### ISSUE TITLE
Uploading UTF-8 encoded file with Hungarian accented letters

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sensenet#483]
I tried to upload a file named Bőszájú körülíróművész.txt with this content:
Csúszdázó műbőr különítmény
Húsz kábító fűrész őrködik, üt.
Fűsújtó, sárgördítő ütés
Gyümölcsvédő ágyúfűnyíró
Háztűznézőügynök-búsító
Jóhírű tüzérágyúöntő
Jóízű félárú sütőtök

but the uploaded file contains this:

CsÃºszdÃ¡zÃ³ mÅ±bÅ‘r kÃ¼lÃ¶nÃ­tmÃ©ny
HÃºsz kÃ¡bÃ­tÃ³ fÅ±rÃ©sz Å‘rkÃ¶dik, Ã¼t.
FÅ±sÃºjtÃ³, sÃ¡rgÃ¶rdÃ­tÅ‘ Ã¼tÃ©s
GyÃ¼mÃ¶lcsvÃ©dÅ‘ Ã¡gyÃºfÅ±nyÃ­rÃ³
HÃ¡ztÅ±znÃ©zÅ‘Ã¼gynÃ¶k-bÃºsÃ­tÃ³
JÃ³hÃ­rÅ± tÃ¼zÃ©rÃ¡gyÃºÃ¶ntÅ‘
JÃ³Ã­zÅ± fÃ©lÃ¡rÃº sÃ¼tÅ‘tÃ¶k

![image](https://user-images.githubusercontent.com/39081660/46211133-04700a00-c333-11e8-89a8-1c09cee26766.png)

Could not test creating directly (https://app.zenhub.com/workspace/o/sensenet/sensenet/issues/477)

**Comment by tusmester** [comment]
closed as cannot be reproduced
