### ISSUE TITLE
Will have plan to support Postgresql/Mysql database?

### ISSUE THREAD

**Issue by HengzheLi** [SenseNet/sensenet#489]
Support any free or opensource database?

**Comment by HengzheLi** [comment]
Thanks for the reply. 

Does it mean if there is a Postgresql/Mysql provider, then it will port to Postgresql/Mysql?
I already have those two db runing in a Linux. Just want to know if there is possible running Senenet without installing the third database.

**Comment by tusmester** [comment]
In the future if there will be a postgresql/mysql provider, it will be possible to migrate data from one db (e.g. SQL Express) to another (e.g. mysql) by **exporting and importing content**, yes. Hope I understood the question correctly.

**Comment by HengzheLi** [comment]
OK. Thanks. your understood is correct.
