### ISSUE TITLE
[WOPI] Host page for documents in the browser

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#504]
To display documents in the browser, we need a **host page** that will host the Office Online iframe.

- https://wopi.readthedocs.io/en/latest/hostpage.html#host-page

> **Move this issue** to the appropriate repo when we start working on it.

**Comment by tusmester** [comment]
I think we should provide an action only for the tokens and urls required by the html in the example above. The html should be assembled on the client and _not_ served by the server. 
@gallayl ?

**Comment by herflis** [comment]
- [ ] add an example to the dms
- [ ] discuss if part of the code could be outsourced to another package(s)
- [ ] discuss header and/or navigation back to the doclib

**Comment by herflis** [comment]
Issue moved to [SenseNet/sn-client #194](https://github.com/SenseNet/sn-client/issues/194) via [**ZenHub**](https://www.zenhub.com/)
