### ISSUE TITLE
Sensenet works in Azure SQL

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#51]
- [x] Azure SQL Database settings alteration
- [x] Install database script sql authentication
- [x] Don't forget to check if the settings are good for mssql as well
- [x] Have another user install sensenet using azure sql
- [x] Add Azure db info to the [install from nuget](https://github.com/SenseNet/sensenet/blob/develop/docs/install-sn-from-nuget.md) docs

**Comment by borsi** [comment]
Update the "install-sn-from-nuget" doc at the "create the database" part so users would know they can install SN on an Azure SQL db as well.

**Comment by tusmester** [comment]
Installed it on Azure SQL successfully.
:shipit:
