### ISSUE TITLE
Querying on a content's reference field

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sensenet#515]
I've tried to write a query on a content's reference and executed it on both sn 6.x and the latest 7 and it gave me a different result.
`/odata.svc/Root?$select=Path,Name,ModifiedBy&$expand=ModifiedBy&$orderby=IsFolder%20desc,DisplayName%20asc&query=ModifiedBy:{{Name:"alba"}}&metadata=no`

In sn6, I've received the expected standard collection response, in SN7 I've got the following exception:
```json
{
    "error": {
        "code": "NotSpecified",
        "exceptiontype": "ParserException",
        "message": {
            "lang": "en-us",
            "value": "Syntax error, (query:  +(ModifiedById:{{Name: alba }}) +(InTree: /Root ) ) [Line: 1, Col: 17]"
        },
        "innererror": null
    }
}
```
Are these types of reference queries supported in SN7? *(e.g. Reference:{{ReferenceField:"something"}})*

If not, do we have any alternatives for filtering in references?

**Comment by kavics** [comment]
"Are these types of reference queries supported in SN7": Yes but it was buggy. The previous big IR refactor temporarily hides this functionality. It is fixed in #512.
