### ISSUE TITLE
Add comments content structure changes from patch

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sensenet#555]
to be defined

- New Comment CTD (and replies...?). Place where the preview content is located, under the file in services.
- Create a folder for holding comments under File's content template
- Create the comments folder under all files with correct permissions

**Comment by herflis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Comments in DocViewer](https://trello.com/c/H68guu6E/2-comments-in-docviewer)
