### ISSUE TITLE
[Storage] DataHandler refactor/reissue

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#556]
As a developer I want to use a modern extensible abstract data-storage interface instead of an MSSQL-bound code set. 

#### Requirements
- asynchronous API
- platform-independent API (do not use platform specific types)
- simple and extendable (move feature-specific parts to db provider extensions)
- use `IDbCommand`, `IDbDataParameter` interfaces to encapsulate the custom data provider scripts
- avoid static implementations to make parallel testing easier

**Comment by herflis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DataHandler refactor/reissue](https://trello.com/c/jRjMazSl/1-datahandler-refactor-reissue)
