### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#56]
The test project (with approximately 1300 tests) is not suitable for regular execution (run as per-commit test). Test cases within this project must be implemented in the appropriate component (mainly in the services). It would be better if this issue will generate more smaller stories (one theme per story e.g. odata or notification). The original project - after heavy cleaning - can continue to work as system tests (or beta tests or any other buzzword). In this case these tests must be executed before releasing the product.

**Comment by borsi** [comment]
### Tasks to think about
**Move the integration test cases to the Sensenet.Services component**
  - Content query related tests
  - OData related tests

**Determine the interfaces**
- IDataProvider
- Indexing service interface
