### ISSUE TITLE
[SPIKE] New data storage API

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#591]
Create an experimental alternative of the abstract DataProvider and related objects. Requirements:
- Simple
- Async
- Extendable
- Instance (avoid static members)
- Platform independent (Relational / NoSQL / InMemory)

Proof of new API correctness:
- All tests are green when the persistence layer is an in-memory implementation of the new API.

Tasks
- [ ] Explore all dependencies of the database objects (tables/views/procs etc. in scripts/code files etc.).
- [ ] Rewrite all procedure's algorithms to pseudocode for easy rewriting and documentation (warning: some proc contains hardcore business logic).
- [ ] Eliminate static methods (BREAKING CHANGE).
- [ ] Delete feature that calls direct SQL (e.g. journal, appmodell script), or rewrite that to an abstract method (BREAKING CHANGE).
- [ ] Create a wrapper provider for the old API that able to execute side-by-side the old and new implementation.
- [ ] Create a document-based concept for an in-memory data provider to prototype any no-sql implementation.
  - [ ] Specify the document (or documents if there is no way to use any joining technology).
  - [ ] Plan a general technique for loading level (head - meta - full)
- [ ] Write the CRUD operations of the Node to demonstrate the correctness of the concept. Expected providers: MSSQL + in memory (no-sql).
- [ ] ???

**Comment by herflis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DataHandler refactor/reissue](https://trello.com/c/jRjMazSl/1-datahandler-refactor-reissue)
