### ISSUE TITLE
[Storage] New SQL dataprovider

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#595]
#### PERFORMANCE RELATED TASKS
- [x] Discussion: can we remove the IBlobStorageMetaDataProvider functionality?
- [x] BLOB-STORAGE
  - [x] Use BlobStorage in Storage\Data\RelationalDataProviderBase.CopyAndUpdateNodeAsync
  - [x] Copy BinaryProperies via BlobStorage (MsSqlDataProviderScripts, RelationalDataProviderBase x2
  - [x] DISCUSSION: What about SQLFS implementations (can we remove the 
  - [x] ASYNC API in whole BlobStorage API and IBlobStorageMetaDataProvider
  - [x] Review when CancellationToken is not used.
- [x] ASYNC API: use ConfigureAwait(false) calls everywhere
- [x] ASYNC API: Check DataContext creation without CancellationToken.
- [x] ASYNC API: Review all usage of `CancellationToken.None`.
- [x] ~REFACTOR: Move script (split by the current algorithm)~

#### CODE QUALITY
~- [ ] InMemoryIndex thread safety (sometimes there is an ArgumentOutOfRangeException in the  InMemoryIndex.cs line 194).~
- [ ] TESTS
  - [x] Fix inconclusive packaging tests in the Tests\SenseNet.Packaging.Tests\StepTests\DeleteContentTypeTests.cs
  - [x] Missing test for LoadNodeHeadsFromPredefinedSubTeesAsync
  - [x] MsSqlDP_Move
    - [x] Choose and check that NodeTimestamp needs to refresh or not.
    - [x] Check assertions without clearing cache explicite
  ~- [ ] TEST MIGRATION from SN6.5~
    ~- [ ] Get **Copy** unit tests~
    ~- [ ] **Copy** integration tests (subset of unit tests).~
    ~- [ ] **Move** unit tests (convert all existing integration tests to unit tests and delete not-sql integration tests.~
    ~- [ ] Get any other relevant unit/integration tests~
- [x] NOT IMPLEMENTED
  - [x] Implement or move to ITestingDataProviderExtension implementations
    - [x] SetSharedLockCreationDate in Storage\Data\MsSqlClient\MsSqlSharedLockDataProvider
    - [x] LoadNodeHeadsFromPredefinedSubTeesAsync in Tests\SenseNet.Tests\Implementations\InMemoryDataProvider
    - [x] GetSharedLockCreationDate in Storage\Data\MsSqlClient\MsSqlSharedLockDataProvider
  - [x] InitialData
    - [x] Load-save the initial ContentTypeDefinitions
	- [x] Load-save the initial Blobs

**Comment by herflis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DataHandler refactor/reissue](https://trello.com/c/jRjMazSl/1-datahandler-refactor-reissue)
