### ISSUE TITLE
[Storage] Documentation: new db provider

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#596]
- [x] DataStore (static): for system developers and for us.
- [x] DataProvider (abstract): for platform implementers.
   - [x] IDataProviderExtension
   - [x] IAccessTokenDataProviderExtension [Access token](https://community.sensenet.com/docs/accesstoken).
   - [x] IPackagingDataProviderExtension
   - [x] ISharedLockDataProviderExtension
   - [x] ITestingDataProviderExtension
- ~derived built-in db provider implementations~
   - ~Relational~
   - ~MS SQL~

**Comment by herflis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DataHandler refactor/reissue](https://trello.com/c/jRjMazSl/1-datahandler-refactor-reissue)
