### ISSUE TITLE
New Data Storage API

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#597]
Create a new abstract DataProvider and related objects as Data Storage API. Requirements:
- Simple
- Async
- Extendable
- Instance (avoid static members)
- Platform independent (Relational / NoSQL / InMemory)

**Comment by herflis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DataHandler refactor/reissue](https://trello.com/c/jRjMazSl/1-datahandler-refactor-reissue)
