### ISSUE TITLE
Wopi Edit action should not be available on old Office files.

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#627]
`WopiOpenAction` decides whether the action is available based on the permissions of the current user and the extension of the file. In case of `doc` (not docx) files this is not enough, because they can be viewed but not edited.

The action should take the type of the action (view or edit) into account when determining the availability of the action.

**Comment by gallayl** [comment]
There is another scenario with PDF files. If you upload a PDF, the **WopiOpenEdit** and **WopiOpenView**  will be available, and
 - when I try to open the file, the edit mode, **GetWopiData** fails (so this the scenario is similar)
 - when I try to open for read, I got the token from **GetWopiData**, but the Office Online displays the following error message:
![image](https://user-images.githubusercontent.com/16716099/59746673-ae077a80-9277-11e9-81d0-0e7e3fef059e.png)

Is there a way to discover the capabilities of the Office Online server and allow **WopiOpenEdit** and **WopiOpenView** based on that?
