### ISSUE TITLE
After-refactor metrics on the 1000 content demo

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#648]
Check the following things on the demo db after the dataprovider refactor:

#### Whole database
- [x] Db size [ALLOCATED] + log
- [x] Db size [USED]
- [x] Files table
- [x] Versions table

#### In the Content subtree (count)
- [x] Files
- [x] Preview images
- [x] Folders
- [x] SystemFolders

#### In the Content subtree (size, binary+indexdoc)
- [x] All
- [x] Docs
- [x] Preview images

Old stuff:
--------
**Whole database**
Db size [ALLOCATED]	37 200 MB (33 GB dB + 4 GB log)
Db size [USED]	18 420 MB
Files table	2 551 MB
Versions table	15 816 MB

**In the Content subtree (size, binary+indexdoc)**
All 17 936 MB
Docs 17 575 MB
Preview images 361 Mb

**Comment by VargaJoe** [comment]
Whole database
------------------------------
Db size [ALLOCATED]	:  MB (Gb db + Gb log) 
Db size [USED]		:  MB
Files table			: 2 552 MB
Versions table			: 16 431 MB

In the Content subtree (count)
------------------------------
Files 			: 781
Preview images	: 2220
Folders			: 30
SystemFolders		: 1383

In the Content subtree (size, binary+indexdoc)
------------------------------
All  				:  18 541 MB
Docs			:  18 064 MB
Preview images	:  357 MB
