### ISSUE TITLE
Docs: port articles from wiki: REST api, Smart app model, Portlet, WebDav

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#65]
Port these articles from wiki, because they are referenced from new docs here on github:

- [x] http://wiki.sensenet.com/Smart_Application_Model
- [x] http://wiki.sensenet.com/OData_REST_API
- [x] http://wiki.sensenet.com/Portlet
- [x] http://wiki.sensenet.com/Webdav
- [ ] Update the links here in the **install-sn-from-nuget.md** and **sensenet-components.md** files.

**Comment by borsi** [comment]
Should we also move the images to our sn-resources repository?

**Comment by tusmester** [comment]
We agreed on storing images for docs locally in the repo where the doc is created, in the **docs/images** subfolder.
