### ISSUE TITLE
[BUG] CORS origins containing dashes

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#674]
*.netlify.com is added as allowed origin but requests from 
[https://5d765b0ee8c194541461c0bc--sn-app-dev.netlify.com](https://5d765b0ee8c194541461c0bc--sn-app-dev.netlify.com) or
[https://sn-app-dev.netlify.com/](https://sn-app-dev.netlify.com/) result cors errors that they are not allowed origins.
The issue is solved if I add the whole url to the settings file, so it should be related to the dash characters in the url.

**Comment by tusmester** [comment]
**Solution**: extend the regex in the `GetAllowedDomain.HttpHeaderTools` method.

**Comment by geisterfurz007** [comment]
This can be closed or is there anything that still needs to be done?

If so, I would be happy to do so but with a merged PR, it doesn't look like it ^^
