### ISSUE TITLE
install-syncad2portal  failed with does not allow type...

### ISSUE THREAD

**Issue by marosvolgyiz** [SenseNet/sensenet#677]
Hi, 

I installed Sensensenet Servicese 7.6.1.

I tried install syncad2portal from nuget. The packege downloaded, and the code build as succesfully. When I try install with sn-admin, I get the following error:
[install_adsync_issue](https://user-images.githubusercontent.com/26160248/64939134-7c935080-d860-11e9-8808-b1b44d5ebd7c.png)

Br,
maros

**Comment by tusmester** [comment]
Issue moved to [SenseNet/sn-adsync #2](https://github.com/SenseNet/sn-adsync/issues/2) via [**ZenHub**](https://www.zenhub.com/)
