### ISSUE TITLE
Port documentation from wiki: .Net API

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#684]
Port old articles from wiki and refresh them for sensenet 7. The new article should be an .md file in the sensenet repository's _/docs_ folder. Old screenshots should be remaked on the new [admin-ui](https://admin.sensenet.com) if it is possible and placed into the _/docs/images_ folder.

- [ ] [.Net API](http://wiki.sensenet.com/Most_common_API_calls)

**Comment by mohatagarvit** [comment]
Hi, I'll like to take this one.

Is there any specific way we want the special notes in the blue box to appear? Or should they be treated like other text?

**Comment by herflis** [comment]
Hi @mohatagarvit blue box content should be placed in a [blockquote](https://www.markdownguide.org/basic-syntax/#blockquotes-1)
