### ISSUE TITLE
Port documentation from Wiki: Settings

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#686]
Port old articles from wiki and refresh them for sensenet 7. The new article should be an .md file in the sensenet repository's _/docs_ folder. Old screenshots should be remaked on the new [admin-ui](https://admin.sensenet.com) if it is possible and placed into the _/docs/images_ folder.

- [ ] [Settings](http://wiki.sensenet.com/Settings)

**Comment by brittanyjoiner15** [comment]
Just so i understand i'm taking that page and putting it in and MD file and then added to the folders listed above, correct?

**Comment by herflis** [comment]
@brittanyjoiner15 it is correct :)

**Comment by brittanyjoiner15** [comment]
@herflis sweet! I'll work on this!

**Comment by brittanyjoiner15** [comment]
title:  "Settings"
source_url: 'http://wiki.sensenet.com/Settings'
category: Concepts
version: v6.0
tags: [fields,]

Can you clarify what these pieces should be?

**Comment by herflis** [comment]
title:  "Settings"
source_url: “https://github.com/SenseNet/sensenet/blob/master/docs/settings.md”
category: Concepts
version: v6.0
tags: [settings, config]

**Comment by brittanyjoiner15** [comment]
Okay think I've got it! Let me know if there's anything I need to fix here: https://github.com/SenseNet/sensenet/pull/704
