### ISSUE TITLE
Local IIS host is not working

### ISSUE THREAD

**Issue by lhslll** [SenseNet/sensenet#688]
when I following the guide to install from nuget on a ASP.net MVC application, browse default_site 404 alway in local IIS, but it is working when use IIS express.

**Comment by tusmester** [comment]
Hi, can you please add more details?
- you installed the Services and WebPages packages of sensenet, is that correct?
- what url do you use when accessing the site through IIS Express and IIS?

**Comment by herflis** [comment]
@lhslll , if you still face this issue, feel free to open this issue again, but now we close it, sorry
