### ISSUE TITLE
Windows (NTLM) auth does not work

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#69]
With or without the WebPages component installed, the **Windows (NTLM) auth feature does not work** (it is easier to test it with WebPages installed though).

- install sensenet Services and WebPages
- create a user in the repo for your domain account under a correct domain (_sn_, not builtin!)
- add a _site_ in sensenet with a custom url with Windows auth defined on it
- register that url on your machine in the _hosts_ file
- create an IIS site pointing to the web folder and register the url binding
- switch on Windows auth on the IIS site
- start the site in IIS and attach with VS

--> when the site starts to load, the browser pops up a **login dialog** (it should not), even if you are already logged in to Windows with your domain account. If you try to log in, it fails, the request arrives to SN, but without the authenticated user.

Possible causes:
- missing web.config entry?
- incorrect IIS configuration?
- something is wrong with our modules? (authenticate/portalcontext/authorize)

Related to #10

**Comment by iviczl** [comment]
It turned out to be some configuration mistake.
