### ISSUE TITLE
Port documentation from Wiki: How to create a new class for source code

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#695]
Port old article from wiki and refresh them for sensenet 7. The new article should be an .md file in the sensenet repository's /docs folder. Old screenshots should be remaked on the new admin-ui if it is possible and placed into the /docs/images folder.

The .md file should have the following header:

```
---
title: %title%
source_url: %url of the file on github%
category: Development
version: v7.0.0
tags: %possible tags as an array%
---
```

(you can use [these doc](https://github.com/SenseNet/sensenet/edit/master/docs/blob-provider.md) as example)

[How to create a new class for source code](http://wiki.sensenet.com/How_to_create_a_new_class_for_source_code)

**Comment by msdeibel** [comment]
I'll take this one.
