### ISSUE TITLE
Documentation needed for admin UI APIs

### ISSUE THREAD

**Issue by arimanyus** [SenseNet/sensenet#715]
I believe that a documentation is urgently needed for APIs. The whole project, in general, lacks documentations and guide about multiple things.

**Comment by herflis** [comment]
Hi @arimanyus , yes, you're right a lot of documentation is needed, and it is in progress to create them one by one 🙂 Check [this issue](https://github.com/SenseNet/sensenet/issues/632) where I tried to list all the docs that is needed 'urgently'. Do you see anything here that is missing from the list and you would read about? What do you think, which one of them should be done first?

**Comment by arimanyus** [comment]
Thank you for the comprehensive list. A general guide on the admin-ui could be done, as mentioned under 'end user docs for admin-ui', I believe.

**Comment by AkkiBond** [comment]
@herflis I've done documentation for 'what is JAMstack' and pulled request. Please check it once.

**Comment by herflis** [comment]
Our new documentation site is up and running :) Check out the _API Docs_ and a _Guides_ menus [https://docs.sensenet.com/](https://docs.sensenet.com/)
