### ISSUE TITLE
Pdf text extract does not work properly

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#74]
There should be a text extract functionality in Services, but it looks like it does not extract much text from pdf's. @kavics knows more about the issue, please share any relevant info here.

**Comment by kavics** [comment]
The issue is triggered by the missing PDF IFilter on the benchmark webservers. After installing the appropriate component, the test extracting works properly. 
**Existing an appropriate PDF IFilter on every web node is a prerequisite of the installing SenseNet.Services.**
