### ISSUE TITLE
[Components]: Workflow

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#76]
Create a separate repository for the **workflow feature** and publish it as NuGet packages.

- [x] one dll-only package for the workflow libraries (_SenseNet.Workflow_)
- [x] one install package (_SenseNet.Workflow.Install_) - creates the wf tables, imports content types etc.
- [x] the install package adds views, pages (GUI-related stuff) only if the _WebPages_ component is present.
- [x] the install package adds certain items (e.g. Mailprocessor wf) only if the Workspaces component is present.
- [x] another dll package for GUI classes that can be installed only if WebPages is present (_SenseNet.Workflow.Portlets_?)
- (_later, optionally_) set demo workflows on demo lists (under Default_Site/workspaces) as in previous demo systems (e.g. a predefined approval in one list)

## Acceptance criteria
- [x] Tried by 1 person other than @tusmester 
- [x] The install works
- [ ] Approval workflow works
- [x] Public registration workflow runs without a hitch

**Comment by borsi** [comment]
#52 is a releaseblocker for this
