### ISSUE TITLE
ValidateCredentials action

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#760]
Create a new OData action (`ValidateCredentials`). 

- do not modify the repo,
- do not log in the user
- return `200 OK`, and maybe `true` (?) if the user exists and the password is correct
- parameters: `username` and `password` on a POST request body

### To be decided
This action _may_ need to return some info about the user so that the IS4 server can continue logging in the user. This will be determined when the IS4 module reaches the state when it can be integrated with the other components.

**Comment by consolelogreece** [comment]
I would like to try this one if that's okay

**Comment by tusmester** [comment]
Sorry @consolelogreece , this is something that is under discussion and not ready for development yet :). Please look for issues marked by the `hacktoberfest` label.

**Comment by consolelogreece** [comment]
My bad @tusmester , It looks like all the hacktoberfest issues have already been claimed. Are there any others that need doing?
