### ISSUE TITLE
Grammer mistake in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Neilblaze** [SenseNet/sensenet#781]
Here the word "awesome" is placed doubly side by side, one without hyperlink extension(left one) and the adjacent other one with hyperlink!

I have pulled a request regarding this for a fix. Kindly merge it. Thanks :)
https://github.com/SenseNet/sensenet/issues/744
![dwdsdw](https://user-images.githubusercontent.com/48355572/67022269-97d2d380-f11e-11e9-8f0d-bfdfcf5f0dab.JPG)

**Comment by Neilblaze** [comment]
Here is the updated pull request:|
https://github.com/SenseNet/sensenet/pull/780

**Comment by raghavdhingra** [comment]
I have solved the issues and checked for all the grammatical mistakes, errors and typos.
