### ISSUE TITLE
Cannot open a doc in office online 

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#830]
Cannot open a doc in office online, neither for editing nor for reading

Steps to reproduce:
1. Go to the [admin-ui](https://5dca7aa564c7c9a8cbadb9a5--sn-app-dev.netlify.com/) (this is now a test site on a [pull request](https://github.com/SenseNet/sn-client/pull/454))
2. Navigate to a doclib's folder (e.g. content/it-workspace/document library/Chicago)
3. Right-click on one of the docx files (BusinessPlan.docx for example)
4. Choose WopiOpenEdit or WopiOpenView from the context menu

![image](https://user-images.githubusercontent.com/6968860/68747358-a9fb4100-05fa-11ea-8ceb-5f3491585645.png)

**Comment by tusmester** [comment]
This was an internal network/communication issue and has been resolved without code changes.

**Comment by herflis** [comment]
@tusmester It was not moved to Done yet, because it has to checked with all the demo repositories, so I move is back to Review :)
