### ISSUE TITLE
[BUG?]Visitor need to have see permission on itself to get children of a public content

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#870]
If you want to publish children of a content for everyone even for visitors you are unable to do it with giving the Visitor open on the container and runapp on the Browse application.

[https://docs.service.sensenet.com/OData.svc/Root/Content('docs')?$select=DisplayName&metadata=no](https://docs.service.sensenet.com/OData.svc/Root/Content('docs')?$select=DisplayName&metadata=no)

```
{
  "d": {
    "DisplayName": "docs"
  }
}
```

[https://docs.service.sensenet.com/OData.svc/Root/Content/docs](https://docs.service.sensenet.com/OData.svc/Root/Content/docs)

```
{
  "error": {
    "code": "NotSpecified",
    "exceptiontype": "SenseNetSecurityException",
    "message": {
      "lang": "en-us",
      "value": "Access denied."
    },
    "innererror": null
  }
}
```

I've checked the error in the eventviewer:
![image](https://user-images.githubusercontent.com/6968860/72896483-28bdda00-3d20-11ea-8ffd-8365167feb23.png)
**Access denied. Path: /Root/IMS/BuiltIn/Portal/Visitor PermissionType: See User: BuiltIn\Visitor**

After giving see permission for the Visitor everything works like charm. 

Please allow see permission for Visitor user on itself somewhere in the core product install/import

**Comment by tusmester** [comment]
Done in #1039
