### ISSUE TITLE
SnAdminRuntime: different patch dlls per phase

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#9]
Currently **SnAdminRuntime** always loads custom patch dlls from the hardcoded "_PackageCustomization_" subfolder inside the executed package. It would be useful if we allowed the package maker to ship **multiple different patch libraries** for different **phases** inside a single package. 

A typical use case for this is when we have to execute a custom step compiled with the old SN libraries, than other custom steps compiled with the new ones. These two types of custom steps cannot live in the same assembly and cannot be added to a single package now, because the runtime always loads custom dlls from the folder mentioned above.

**Solution** (_updated_): let the package creator define _folders for each phase_, containing custom libraries that are loaded only for that phase. 

We keep the current behavior (if you put a folder called _PackageCustomization_ into your package, we will load those dlls for all phases), and if you **define a folder explicitly** in the **extensions** attribute of a Phase, we will load those dlls only for that phase.

`<Phase extensions="PackageRelativePath">`

**Comment by kavics** [comment]
It can be a better way to configure the additional assembly source in the phase. For example:
<Phase extensions="RelativePathOfMyAdditionalAssembliesDirectory"> ...

**Comment by tusmester** [comment]
That is what I wanted to avoid, having to explicitly add this to the manifest. As a package creator, why do I have to do that? Why do not we use an automatism like now, only extended with an optional phase index?

**Comment by kavics** [comment]
Because the explicit source is more straightforward approach I think

**Comment by tusmester** [comment]
Ok, deal. We keep the current behavior (if you put a folder called PackageCustomization into your package, we will load those dlls for all phases), and if you define a folder explicitly in the extensions attribute of a Phase, we will load those dlls only for that phase.

**Comment by tusmester** [comment]
Closed by #31
