### ISSUE TITLE
sensenet should not allow duplicates of AllowedChildTypes items

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sensenet#909]
On admin ui there is a possibility to add the same type twice (or more) to AllowedChildTypes field.

**How to reproduce:**
1. Admin ui login (with admin)
2. Open 'Content' drawer-> Right-click on 'IT Workspace' -> EDIT
3. On 'Allowed child type' field type Application (add with + button)
4.  step 3 again
5. Submit

There is no error message from the server to avoid duplicates.
Could you please respond with an error in this case? Thank you!

**Comment by tusmester** [comment]
Why do we want to throw an error in this case? Not very user-friendly. Why can't we filter the list on the server and save it silently? 
@kavics @herflis
