### ISSUE TITLE
Schema contains wrong localization values

### ISSUE THREAD

**Issue by pusztaienike** [SenseNet/sensenet#914]
After update a localization file, the new schema contains wrong values.

E.g: 
I have changed the localization file of Group (CtdResourcesGH.xml). I set the displayName for Members field to: Membersxxx, I saved the file, the schema generated, but in the schema worng value was for the displayName of Members (the value was: Members).
![2020-03-25_10h55_27](https://user-images.githubusercontent.com/22347393/77533800-cf953280-6e97-11ea-9a95-4c999a5c9d67.png)
![2020-03-25_10h56_05](https://user-images.githubusercontent.com/22347393/77533801-d0c65f80-6e97-11ea-9ae9-23240a8ec405.png)
```
      {
        "AllowMultiple": true,
        "AllowedTypes": [
          "User",
          "Group"
        ],
        "SelectionRoots": [
          "/Root/IMS/Public",
          "/Root"
        ],
        "Type": "ReferenceFieldSetting",
        "Name": "Members",
        "FieldClassName": "SenseNet.ContentRepository.Fields.ReferenceField",
        "DisplayName": "Members",
        "Description": "The members of this group.",
        "ReadOnly": false,
        "Compulsory": false,
        "OutputMethod": 0,
        "Visible": true,
        "VisibleBrowse": 0,
        "VisibleEdit": 0,
        "VisibleNew": 0,
        "DefaultOrder": 20
      },
```

**Comment by tusmester** [comment]
We should reset the client metadata provider cache when resources change. The problem is that currently there is no event  for that (resource manager is in the content repository layer, the metadata provider is up in the OData layer).
