### ISSUE TITLE
[Client.NET] Missing template resolution in ContentQuery

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#933]
The template in a CQL causes an exception.
```csharp
var result2 = await Content.QueryAsync(
    "TypeIs:User +CreationDate:<@@CurrentWorkspace.Manager.CreationDate@@");
```
throws this:
```
SenseNet.Search.Querying.Parser.ParserException:
'Cannot parse the value. FieldName CreationDate, Parser: DateTimeIndexHandler,
(query: "+(TypeIs:User +CreationDate:<@@CurrentWorkspace.Manager.CreationDate@@) +(InTree:'/Root')")
[Line: 1, Col: 71]'
```

**Comment by kavics** [comment]
There is no template replacer that can resolve the CurrentWorkspace entity. To fix this bug we should choose:
- Port from somewhere or develop a new template replacer.
- Remove tests and documentation for this case.

**Comment by herflis** [comment]
I reviewed the docs and changed the occurrences of CurrentWorkspace template parameter to CurrentUser (where it was possible) and removed the example where it was the only option (workspace trash).
