### ISSUE TITLE
[OData] string array parameters are not recognized

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#973]
If an OData action method has a string array parameter (for example `HasPermission(permissions)`), the current backend mechanism does not recognize the array sent in the request (in this case in the URL, as this is a GET request).

##### Solution
The `OperationCenter.TryParseParameter` method should be able to convert string parameters in the request to a string array if that is expected. **Consider expanding this to other types**, e.g. int/bool arrays.

**Comment by kavics** [comment]
Please provide a simple code that makes the problem clear or describes your expectations.

There are a number of green tests for methods that have required or optional array or list called from querystring. See the followings:
- old
  - OD_MBO_Call_Array_QueryString
  - OD_MBO_Call_List_QueryString
  - OD_MBO_Call_Enumerable_QueryString
- new
  - OD_MBO_BuiltIn_HasPermissions
  - OD_MBO_Call_Array_Optional_QueryString
  - OD_MBO_Call_List_Optional_QueryString
  - OD_MBO_Call_Enumerable_Optional_QueryString

**Comment by herflis** [comment]
@kavics 

## Example url:

https://dev.demo.sensenet.com/odata.svc/content(1081)/HasPermission?permissions=Open,Approve

## Response:

```
{
  "error": {
    "code": "UnknownAction",
    "exceptiontype": "InvalidContentActionException",
    "message": {
      "lang": "en-us",
      "value": "Operation not found: HasPermission(permissions)"
    },
    "innererror": null
  }
}
```
